### ISSUE TITLE
Where is the build job configuration for fedora-realtime-container-disk

### ISSUE THREAD

**Issue by zhlhahaha** [kubevirt/kubevirtci#1002]
Currently, I am trying to push the PR for build multi-arch fedora-realtime-container image, in order to do E2E tests. However, I can not find the build configuration for this image. I can see the image is keeping updating in the repository https://quay.io/repository/kubevirt/fedora-realtime-container-disk?tab=tags

For more details, please refer to the comments in https://github.com/kubevirt/project-infra/pull/2630#issuecomment-1496377730

**Comment by brianmcarey** [comment]
These are built and pushed as part of the nightly kubevirt build.
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-push-nightly-build-main/1648492313854349312#1:build-log.txt%3A665

**Comment by zhlhahaha** [comment]
I see, although it is tag with arm, but it still use x86_64 fedora image. Thanks Brian.
