### ISSUE TITLE
One of KubevirtCI's image layers is significantly larger than others which leads to a slow image pull

### ISSUE THREAD

**Issue by iholder101** [kubevirt/kubevirtci#1073]
During `make cluster-up`, KubevirtCI's container image is being pulled. Usually this looks like the following:

```
time="2023-08-29T08:32:31Z" level=info msg="Using remote image quay.io/kubevirtci/k8s-1.27:2308161739-3ec1c7b"
Downloading ....................................................................................................
```

When pulling this image manually, we would get into the following situation:
```
> docker pull quay.io/kubevirtci/k8s-1.27:2308161739-3ec1c7b
2308161739-3ec1c7b: Pulling from kubevirtci/k8s-1.27
3a2ddb3f9dd9: Pull complete 
289a6b001fc0: Pull complete 
83df55e4119f: Pull complete 
fe0c4a46e0b1: Pull complete 
4b008daae1fb: Pull complete 
3811dec3da20: Pull complete 
7a65c0cca3f4: Pull complete 
ed3b3398fe3c: Pull complete 
d8fb10c94d27: Pull complete 
33046f65e409: Pull complete 
ecfb7dadcc34: Downloading [==================>                                ]  1.786GB/3.957GB
```

As we can see, only one image layer is much larger than the others which have all completed. This is a 4GB layer, which is pretty massive.

If we could break this layer into multiple smaller layers, the download could occur in parallel therefore speeding up the process of `make cluster-up` when KubevirtCI image needs to be re-pulled.

p.s. I also think we should remove the `Downloading .....` and show the user the actual podman/docker pull output.

**Comment by iholder101** [comment]
FYI @dhiller @brianmcarey

**Comment by brianmcarey** [comment]
I think that is the last layer which contains the provisioned VM image. I am not sure how we can go about splitting the VM image itself. 

It is 11GB uncompressed.

**Comment by dhiller** [comment]
> I think that is the last layer which contains the provisioned VM image. I am not sure how we can go about splitting the VM image itself.
> 
> It is 11GB uncompressed. ![Screenshot from 2023-08-29 10-23-30](https://private-user-images.githubusercontent.com/21010464/263967912-c8d60b2f-d4c4-476f-a9f3-e04592aeb5f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwNzk4MDUsIm5iZiI6MTcwMTA3OTUwNSwicGF0aCI6Ii8yMTAxMDQ2NC8yNjM5Njc5MTItYzhkNjBiMmYtZDRjNC00NzZmLWE5ZjMtZTA0NTkyYWViNWYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDEwMDUwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkYmY4MjQ5NjE5NDY5ODEzMzg0NWU1N2Q1MDE4NDk5YzQyZWVkOTM0NDczZGYzYjBjZTFkZGFmNWRmYmQ2OTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eRFqAx44U74XMaL_LAQKTAPXfgL2FV_k7QNUj0Il1tI)

If there was a way to create a new layer after every image pre pull. But I have no idea how to do that.
