### ISSUE TITLE
automate centos version bump

### ISSUE THREAD

**Issue by dhiller** [kubevirt/kubevirtci#1086]
#1085 was necessary because the pinned centos version vanished. Therefore we should implement an automated bump.

_Originally posted by @brianmcarey in https://github.com/kubevirt/kubevirtci/pull/1085#pullrequestreview-1643647368_

**Comment by oshoval** [comment]
we discussed it also offline, better to see if it happens again and again
it will be better to not bump it too much otherwise, so we will have less moving pieces

**Comment by brianmcarey** [comment]
/remove-lifecycle stale

this is still something that would be useful

**Comment by brianmcarey** [comment]
This should be handled by https://github.com/kubevirt/project-infra/commit/5ec71d62fab85ee0db8ddcad5b9418ad0f279213

/close
