### ISSUE TITLE
Sometimes starting k8s fails because of no connection to the apiserver

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirtci#112]
This [log](https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/2421/pull-kubevirt-e2e-windows2016/1143212415123460096/build-log.txt?Expires=1561447107&GoogleAccessId=prow-46%40kubevirt-240711.iam.gserviceaccount.com&Signature=a%2BlCTBU%2FRWmT0R%2B68AmcfuqKhPwV51jXJWjp9TR3wzGxyWVCfm5UtWVUpEQkCHnEQ25XkW4TIYTmVjXjMvfNhTP7ul7QapOWoSFegVREuQZpYz2wy1Fd%2F1Uxj8gBEteXCkBKAwJ6RE%2F8bL00hf9Ei%2BA34kQOu6NN4%2B71jhBTCBz1CbOnNQfQqiv9v71kKFDYbNUIpxCObqUn05e8qJCHhvtFiF10gj25XkcP5l6K85dy78Hx0ycXcQtV5SElWdgnYnCKys%2BZdcUz9evfNooobLOPZXm9d%2FuJdPzRIP5u2YW56pHiL5%2FSyUWhQAkBYxTOlNA6BhzrL5MWWVGrv74WLg%3D%3D) shows

```
+ kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f https://raw.githubusercontent.com/coreos/flannel/v0.9.1/Documentation/kube-flannel.yml
Unable to connect to the server: net/http: TLS handshake timeout
provisioning node node01 failed
```

I have seen that lately more frequently.

**Comment by cynepco3hahue** [comment]
IMHO we should run all `kubectl` in the loop, similar to OKD
```
until kubectl something; do
sleep 1
done
```
