### ISSUE TITLE
We should get rid of using 'dockerize' in the cluster nodes VM accommodating container

### ISSUE THREAD

**Issue by ormergi** [kubevirt/kubevirtci#1147]
**What happened**:
The cluster nodes accommodating container image is built with dockerize [[1]](https://github.com/kubevirt/kubevirtci/blob/main/cluster-provision/centos9/Dockerfile#L13-L20), and used just for waiting for the guest VM (the cluster node VM) to become online [[2]](https://github.com/kubevirt/kubevirtci/blob/778521a422893435b98df318b8b0546c13f0b0de/cluster-provision/centos9/scripts/vm.sh#L50).

**What you expected to happen**:
I hope we can find simpler ways to wait for the guest to become online then using dockerize (e.g.: using `timeout .. ssh`) instead of installing dockerize just for that purpose which seems an overkill.

**How to reproduce it (as minimally and precisely as possible)**:

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

[1] https://github.com/kubevirt/kubevirtci/blob/main/cluster-provision/centos9/Dockerfile#L13-L20
[2] https://github.com/kubevirt/kubevirtci/blob/778521a422893435b98df318b8b0546c13f0b0de/cluster-provision/centos9/scripts/vm.sh#L50

**Comment by xpivarc** [comment]
/cc @aerosouund 
Can you have a look at this Ammar?

**Comment by aerosouund** [comment]
Sure
/assign

**Comment by aerosouund** [comment]
@xpivarc @ormergi 
Is this even needed ? to wait until its ready ? why not just implement retries in whatever will ssh ?
i have already done that while working on something else in kubevirtci

```golang
for i := 0; i < 10; i++ {
client, err = ssh.Dial("tcp", net.JoinHostPort("127.0.0.1", fmt.Sprint(s.sshPort)), s.config)
if err != nil {
	logrus.Infof("Attempt %d. Error establishing connection: %s, sleeping 4 seconds", i, err.Error())
	time.Sleep(time.Second * 4)
} else {
	break
    }
}
```
