### ISSUE TITLE
monitoring: Update kubevirtci prometheus stack to more recent versions

### ISSUE THREAD

**Issue by brianmcarey** [kubevirt/kubevirtci#1154]
The monitoring stack that is deployed as part of kubevirtci has not been updated in some time. 

This stack includes a number of services[1] and is based on [kube-prometheus](https://github.com/prometheus-operator/kube-prometheus) :
- alertmanager
- grafana
- node-exporter
- prometheus
- prometheus operator

The manifests for each of these services will have to updated.

Follow the KUBEVIRTCI_LOCAL_TESTING.md document to test the updates locally. 
https://github.com/kubevirt/kubevirtci/blob/main/KUBEVIRTCI_LOCAL_TESTING.md#start-cluster-with-prometheus-alertmanager-and-grafana

As part of this task it may be good to capture the steps taken as part of the upgrade as the document is lacking details:
https://github.com/kubevirt/kubevirtci/tree/main/cluster-provision/k8s/1.29/manifests/prometheus#upgrading

[1] https://github.com/kubevirt/kubevirtci/tree/main/cluster-provision/k8s/1.29/manifests/prometheus

**Comment by dhiller** [comment]
@anishbista60 would you want to work on this still?

@machadovilaca would someone from your SIG be able to help out here?

**Comment by anishbista60** [comment]
@dhiller yes sir.

**Comment by anishbista60** [comment]
@brianmcarey 
Do i need to update the manifest according to the below manifest ? 
https://github.com/prometheus-operator/kube-prometheus/tree/main/manifests

**Comment by brianmcarey** [comment]
> @brianmcarey Do i need to update the above stack's manifest according to the below manifest ? https://github.com/prometheus-operator/kube-prometheus/tree/main/manifests

Yes I think that should be it. I think you would only need to focus on the manifests in the latest provider `k8s-1.31`
