### ISSUE TITLE
Sriov provider - disconnects the node if the interface used to reach it is sriov - capable

### ISSUE THREAD

**Issue by fedepaol** [kubevirt/kubevirtci#139]
The setup script is a bit aggressive and moves all the local interfaces that are sr-iov capable into the kind node's namespace.

If the device used to connect to the host is sr-iov capable itself, what happens is that after moving it into the node's namespace the host gets disconnected. 
There should be a way to filter the interfaces not used for sr-iov testing purpouses.

Two approaches could be:
- provide a static list through an env variable
- skip all the pfs that already own an ip address

(or the combination of the two).

**Comment by fedepaol** [comment]
@booxter that's what I meant by "list to filter" so we are on the same line :smile: . 

The reason why we move all the pfs is that it was that way initially, but there is no need to. The current implementation picks only the first pf uses it to configure the node.

Even if we would pick only "the right amount of pfs" the black list should still need to be implemented in order to skip those interfaces needed.

**Comment by dhiller** [comment]
@fedepaol this can be closed IIUC, right?

**Comment by fedepaol** [comment]
Yep, think so
