### ISSUE TITLE
Missing local storage class in OKD-4.1

### ISSUE THREAD

**Issue by rollandf** [kubevirt/kubevirtci#143]
In k8s-1.15.1, we get a local storage class with pre-provisioned PVs.
It would be useful to get the same with OKD-4.1.

**Comment by slintes** [comment]
I'm currently testing adding local storage in https://github.com/kubevirt/kubevirt/pull/2623, see commit https://github.com/kubevirt/kubevirt/pull/2623/commits/786687df438a5710d594c21951bcae95038c925c
Stolen from CDI repo :sunglasses: 
But probably makes sense to move this into the OKD provider itself.

@awels wdyt?

**Comment by awels** [comment]
So I go back and forth on this. It makes sense to have the provider also provide some storage, but on the other hand it pollutes the provider with something that is not essential. I think we should leave it up to the user of the provider if they want storage and if so what kind. Maybe it makes sense to update cluster-up to look for certain flags to enabled certain storage/  For instance we have the --enable-ceph parameter for k8s provider which doesn't work for any other providers. It would be nice if we could enable that for other providers as well.

So we add a switch in the main cluster-up script that looks for certain --enable-<storage> and calls a matching function. The default function is a no-op, and each provider can implement their specific version.

I don't know maybe I am over engineering this and we simply put the code in the provider and each provider at a minimum provides local storage.

back and forth, and I switch position every few lines of text I write.

**Comment by rollandf** [comment]
I think that a flag is a good solution , and can local storage can be disabled by default.

The current state is that @awels implemented in CDI, @slintes is also implemeting in kubevirt and I will need to do the same for Tier 2 tests.
Would be easier to have it, especially if it is already implemented in k8s.

Thoughts?

**Comment by slintes** [comment]
done in https://github.com/kubevirt/kubevirtci/pull/145

/close
