### ISSUE TITLE
error: the path "/tmp/local-volume.yaml" does not exist (sometimes)

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirtci#160]
I sometimes see `error: the path "/tmp/local-volume.yaml" does not exist` on cluster-up.

Here an example:
https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/2768/pull-kubevirt-e2e-os-3.11.0-multus/1179008179694997504/build-log.txt

**Comment by rmohr** [comment]
/assign @awels 

This happens pretty often on the openshift nodes (never saw it on the k8s ones). Do you have any idea why this coul happen?

**Comment by awels** [comment]
Maybe it is a case of OS-3.11 vs OS-3.11-multus, I see their provision script is slightly different. However I think this is where we copy the manifests into the VM: https://github.com/kubevirt/kubevirtci/blob/master/cluster-provision/cli/cli#L188 and that is the same for all providers.

But I thought the 'cli' script was being deprecated, so I am confused now.

**Comment by rmohr** [comment]
> But I thought the 'cli' script was being deprecated, so I am confused now.

It is still used for provisioning.

**Comment by awels** [comment]
Okay, then I am not sure what is going on, as line 188 is called whenever a new image is created, and thus every VM should have that file in /tmp, unless there is something that removes it, but I haven't found anything like that anywhere.

**Comment by awels** [comment]
Btw the token for the link is expired so I can't look at the actual log file.

**Comment by rmohr** [comment]
ah, just remove the token. It is public accessible.

**Comment by rmohr** [comment]
Maybe there is something strange happening, like that they are copied to `/tmp/tmp` or so ...
We probably need to put some debug statements in a PR.

**Comment by awels** [comment]
Did you notice that there is an error in the log ahead of the missing /tmp/local-volume? 

TASK [openshift_manage_node : Wait for sync DS to set annotations on all nodes] *** that fails

**Comment by rmohr** [comment]
Oh, then things start to make sense. :+1:

**Comment by awels** [comment]
You need me to look into something more, or will you figure out why that is failing? I am guessing that is causing the additional failure with local volume.
