### ISSUE TITLE
no cgroupsv2 support for docker

### ISSUE THREAD

**Issue by dhiller** [kubevirt/kubevirtci#171]
I just updated to Fedora 31 recently which upgrades cgroups to v2. Docker does not support cgroups v2, which results in an error when starting the docker daemon.

According to this docker issue[1] and referenced issues it does not sound like docker will support cgroupsv2 soon. From the Fedora perspective[2] it sounds we should use cgroupsv2 rather which podman supports already. There is work ongoing to support `podman` for kubevirtci [3] though an issue exists that prohibits finalization[4].

So what is the thinking about that issue here? Should we just live with the workaround or consider switching to podman? The latter will cause work in kubevirtci, even though podman claims to be a drop in replacement, which is true for the cli side, but not for the api side.

[1] https://github.com/docker/for-linux/issues/665
[2] https://linuxacademy.com/blog/containers/a-game-changer-for-containers-cgroups/
[3] https://github.com/fromanirh/pack8s
[4] https://github.com/fromanirh/pack8s/issues/14

**Comment by dhiller** [comment]
@fabiand @rmohr  @davidvossel  ^^

**Comment by fromanirh** [comment]
I'm confident we can reach a MVP stage on which we can start/stop containers using pack8s if we can work continuously for a week or so. We reached the current stage doing work only in the idle moments last couple of weeks, and we had to stop only because an unforeseen limitation of varlink (see https://github.com/fromanirh/pack8s/issues/14)

**Comment by fabiand** [comment]
+1 for going down the podman path for running our CI.

These days podman should be close to be as universal as docker is.
If somebody needs or wants docker support, then we should ask them to
rpvide the relevant patches.

>

**Comment by slintes** [comment]
Just want to confirm that with the `systemd.unified_cgroup_hierarchy=0` workaround kubevirtci still works on Fedora 31 (which switched to cgroup v2 as default).
Would still love to see podman as 2nd CI runtime, but the workaround takes some pressure away.

**Comment by oshoval** [comment]
we can close right ?

**Comment by dhiller** [comment]
/close

Obsolete
