### ISSUE TITLE
Need to stabilize and test ocp-4.3 provision + push prow lanes end 2 end

### ISSUE THREAD

**Issue by oshoval** [kubevirt/kubevirtci#236]
Need to run those (provision + push) even with current kubevirtci, in order to see the lanes are stable and usable
so when needed we wont get stuck

thanks

**Comment by qinqon** [comment]
Running them here https://github.com/kubevirt/kubevirtci/pull/237, let's see if they work fine.

**Comment by oshoval** [comment]
thanks

**Comment by oshoval** [comment]
/cc @qinqon 
can be closed ?

**Comment by qinqon** [comment]
let's close
