### ISSUE TITLE
--workers-memory param doesn't work in okd 4.1

### ISSUE THREAD

**Issue by ksimon1** [kubevirt/kubevirtci#265]
--workers-memory param (located here: https://github.com/kubevirt/kubevirtci/blob/master/cluster-up/cluster/okd-4.1/provider.sh#L36) doesn't work in okd 4.1

**Steps to reproduce:**
1)`export KUBEVIRT_PROVIDER="okd-4.1"`
2) update --workers-memory 8192 (here: https://github.com/kubevirt/kubevirtci/blob/master/cluster-up/cluster/okd-4.1/provider.sh#L36)  to e.g. --workers-memory 16000
3) `make cluster-up`
4)` oc get node test-1-mkmgt-worker-0-xzq4q -o json | jq '.status.capacity.memory'`

**Actual results:**
"6099376Ki"
**Expected results:**
value around 16Gi

**Log from cluster building:**
```
[ksimon@localhost kubevirtci]$ make cluster-up
./cluster-up/check.sh
[ OK ] found /dev/kvm
[ OK ] intel nested virtualization enabled
./cluster-up/up.sh
Number of workers: 3
you should provide the installer pull secret file, if you want to install additional machines
Download the image docker.io/kubevirtci/okd-4.1@sha256:e7e3a03bb144eb8c0be4dcd700592934856fb623d51a2b53871d69267ca51c86
Downloading .......
Start the container okd-4.1-cluster
Download the image docker.io/library/registry:2.7.1
Downloading .......
Start the container okd-4.1-registry
Run the cluster
+ NUM_SECONDARY_NICS=0
+ chown root:kvm /dev/kvm
+ chmod 660 /dev/kvm
+ haproxy -f /etc/haproxy/haproxy.cfg
+ virsh list
 Id    Name                           State
----------------------------------------------------

++ virsh net-list --name
++ grep -v default
+ cluster_network=test-1-mkmgt
+ virsh net-update test-1-mkmgt add dns-host '<host ip='\''192.168.126.1'\''>
  <hostname>ceph</hostname>
  <hostname>nfs</hostname>
  <hostname>registry</hostname>
</host>' --live --config
Updated network test-1-mkmgt persistent config and live state
+ domain_number=1
++ virsh list --name --all
+ for domain in $(virsh list --name --all)
+ '[' 0 -gt 0 ']'
++ expr 1 + 1
+ domain_number=2
+ virt-xml --edit --memory 12288 test-1-mkmgt-master-0
Domain 'test-1-mkmgt-master-0' defined successfully.
+ virt-xml --edit --cpu host-passthrough test-1-mkmgt-master-0
Domain 'test-1-mkmgt-master-0' defined successfully.
+ [[ test-1-mkmgt-master-0 =~ master ]]
+ virt-xml --edit --vcpu 6 test-1-mkmgt-master-0
Domain 'test-1-mkmgt-master-0' defined successfully.
+ [[ test-1-mkmgt-master-0 =~ worker ]]
+ virsh start test-1-mkmgt-master-0
Domain test-1-mkmgt-master-0 started

+ for domain in $(virsh list --name --all)
+ '[' 0 -gt 0 ']'
++ expr 2 + 1
+ domain_number=3
+ virt-xml --edit --memory 12288 test-1-mkmgt-worker-0-xzq4q
Domain 'test-1-mkmgt-worker-0-xzq4q' defined successfully.
+ virt-xml --edit --cpu host-passthrough test-1-mkmgt-worker-0-xzq4q
Domain 'test-1-mkmgt-worker-0-xzq4q' defined successfully.
+ [[ test-1-mkmgt-worker-0-xzq4q =~ master ]]
+ [[ test-1-mkmgt-worker-0-xzq4q =~ worker ]]
+ virt-xml --edit --memory 16000 test-1-mkmgt-worker-0-xzq4q
Domain 'test-1-mkmgt-worker-0-xzq4q' defined successfully.
+ virt-xml --edit --vcpu 6 test-1-mkmgt-worker-0-xzq4q
Domain 'test-1-mkmgt-worker-0-xzq4q' defined successfully.
+ virsh start test-1-mkmgt-worker-0-xzq4q
Domain test-1-mkmgt-worker-0-xzq4q started

++ virsh list --name --all
++ virsh list --name
+ [[ test-1-mkmgt-master-0
test-1-mkmgt-worker-0-xzq4q != \t\e\s\t\-\1\-\m\k\m\g\t\-\m\a\s\t\e\r\-\0\
\t\e\s\t\-\1\-\m\k\m\g\t\-\w\o\r\k\e\r\-\0\-\x\z\q\4\q ]]
+ export KUBECONFIG=/root/install/auth/kubeconfig
+ KUBECONFIG=/root/install/auth/kubeconfig
+ oc config set-cluster test-1 --server=https://127.0.0.1:6443
Cluster "test-1" set.
+ oc config set-cluster test-1 --insecure-skip-tls-verify=true
Cluster "test-1" set.
+ oc get nodes
Unable to connect to the server: EOF
+ sleep 5
+ oc get nodes
Unable to connect to the server: EOF
+ sleep 5
+ oc get nodes
NAME                          STATUS   ROLES    AGE   VERSION
test-1-mkmgt-master-0         Ready    master   54d   v1.13.4+c41acf267
test-1-mkmgt-worker-0-xzq4q   Ready    worker   54d   v1.13.4+c41acf267
+ sleep 30

```

**Comment by dhiller** [comment]
First of all the parameters are hardcoded in the provider scripts (see i.e. [okd-4.1](https://github.com/kubevirt/kubevirtci/blob/master/cluster-up/cluster/okd-4.1/provider.sh#L36) ). In order to hand edit these we could create some general variables to change these values ad-hoc.
@qinqon @oshoval WDYT?

Second these values are not delivered when [calling the gocli](https://github.com/kubevirt/kubevirtci/blob/master/cluster-provision/okd/4.1/run.sh#L16) so they are not used when entering the vm.
@qinqon @oshoval did I overlook sth here?

**Comment by oshoval** [comment]
in 4.3 it works and we have it setted to 8192 there
okd 4.1 no one use i think anymore, and maybe was even deleted from server (dont know exact details but i wouldnt keep it)

indeed some export WORKERS_MEMORY / MASTER_MEMORY is a good idea 

need to keep in mind a bonus that the gocli set its default which override the provision value
so maybe in the future good to do that gocli wont set a value if no value was given , but it isnt important i guess now ?

**Comment by ksimon1** [comment]
I just put 4.1 there as an example. Btw. 4.3 doesn't work for me as well. All okd 4.* clusters stucks on "waiting for pods to come online" loop (i keep it running for hour, and no change). In container there are about 5 pods which are in pending/creating/oom killed state.

**Comment by oshoval** [comment]
ok, known, thats a different issue of course
sometimes there is a WA
okd provision is blocked until someone test the new libvirt fixes
