### ISSUE TITLE
OCP 4.3 and 4.4 images entry was removed

### ISSUE THREAD

**Issue by djfjeff** [kubevirt/kubevirtci#271]
It seems that https://github.com/kubevirt/kubevirtci/pull/246 reverted the change to https://github.com/kubevirt/kubevirtci/commits/master/cluster-up/cluster/images.sh.

It seems to have reverted the OCP 4.3 sha256 from ocp-4.3@sha256:03a8c736263493961f198b5cb214d9b1fc265ece233c60bdb1c8b8b4b779ee1e to the old ocp-4.3@sha256:8f59d625852ef285d6ce3ddd6ebd3662707d2c0fab19772b61dd0aa0f6b41e5f which does not work anymore :

`2020/02/05 12:10:05 failed to download quay.io/kubevirtci/ocp-4.3@sha256:78c2c7517b3b4d36eebb39e49631340bf6ebf7ac47957612501a43a85fb013ce: Error response from daemon: manifest for quay.io/kubevirtci/ocp-4.3@sha256
:78c2c7517b3b4d36eebb39e49631340bf6ebf7ac47957612501a43a85fb013ce not found`

Setting it back manually to the correct sha256 in the image.sh work correctly :

`Download the image quay.io/kubevirtci/ocp-4.3@sha256:03a8c736263493961f198b5cb214d9b1fc265ece233c60bdb1c8b8b4b779ee1e
Downloading ..`

**Comment by djfjeff** [comment]
It also seems to have removed ocp-4.4 from the file as well.

**Comment by oshoval** [comment]
can be closed, PR by Quique was merged

**Comment by djfjeff** [comment]
Perfect, thank you!
