### ISSUE TITLE
Non-interactive session when ssh to a node in k8s-* provider 

### ISSUE THREAD

**Issue by nunnatsa** [kubevirt/kubevirtci#275]
This issue is from commit `fac568c3691954fabea2b0277c16b5fe2af482d6`.

[Reproduced on a local RHEL-8]

When using a k8s provider, e.g.
``` bash
export KUBEVIRT_PROVIDER=k8s-1.17.0
make cluster-up
```
And then ssh to a node; e.g.
``` bash
./cluster-up/ssh.sh node01
```
The session is not interactive; meaning, anything typed to terminal is ignored, even `echo hello`.

The `USE_TTY` environment variable is not set. Setting it manually at the beginning of the ssh.sh script **does** make it work.

**Comment by oshoval** [comment]
nice find
those git commits show one that work and one doesn't

work 9b8707c02d59ee1a7924103b6beca9b9cd010633
doesnt work 0c3911794ad2b79a61a4bc7462c236251a73866f

**Comment by oshoval** [comment]
also kind providers should be checked as we spoke
thanks

**Comment by nunnatsa** [comment]
kind does work. This is because it handled specifically in ss.sh:
``` bash
elif [[ $KUBEVIRT_PROVIDER =~ kind.* ]]; then
    _ssh_into_node "$@"
else
```
