### ISSUE TITLE
ocp 4.4 image entry was removed

### ISSUE THREAD

**Issue by oshoval** [kubevirt/kubevirtci#276]
guess its by mistake
value appears here

https://github.com/kubevirt/kubevirtci/commit/1f6aaa9846d3f59a846b81811a13a4b81a26b5ae#diff-8e6809c339aac92016edc564e1944acb

**Comment by djfjeff** [comment]
I reported it in https://github.com/kubevirt/kubevirtci/issues/271. There is also an issue with the image for OCP 4.3 that was changed by the same commit.

**Comment by oshoval** [comment]
thanks, so lets close this one and update title of yours to include both ?

**Comment by djfjeff** [comment]
Works for me, I edited the title of my issue.

**Comment by oshoval** [comment]
closing as dupe, thanks
