### ISSUE TITLE
Run `make cluster-up` for openshift providers without sudo

### ISSUE THREAD

**Issue by cynepco3hahue** [kubevirt/kubevirtci#279]
Under 4.3 and 4.4 providers we have line https://github.com/kubevirt/kubevirtci/blob/43c3cadb24cdef3393e1578ca4f71f9bdb968cdf/cluster-up/cluster/ocp-4.4/provider.sh#L56
It tries to echo to some system file, and it can not be done without `sudo` permissions, I expect that we will allow to run `make cluster-up` without `sudo` permissions.

**Comment by danielBelenky** [comment]
https://github.com/kubevirt/kubevirtci/pull/280 fixes this.
