### ISSUE TITLE
Node provisioning fails consistently

### ISSUE THREAD

**Issue by copejon** [kubevirt/kubevirtci#30]
Env(s): Rhel 7.5 (gcloud instance) && Centos 7.5 (local VM in vmware)

I'm following the steps outlined in the main README.md.  In both environments, I get the exact same behavior from 

`# gocli run --random-ports --nodes 3 --background kubevirtci/k8s-1.10.3`

Gives the error

```
{"status":"Status: Image is up to date for docker.io/registry:2"}
2018/07/30 20:55:57 Waiting for host: 192.168.66.101:22
provisioning node node01 failed
```

Logs from `kubevirt-node01`:

```
# docker logs 4a96ea9c8948
3: tap01: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast master br0 state DOWN mode DEFAULT group default qlen 1000
    link/ether 92:41:2b:e4:76:9e brd ff:ff:ff:ff:ff:ff
Creating disk "/var/run/disk/disk.qcow2 backed by /disk01.qcow2".
Formatting '/var/run/disk/disk.qcow2', fmt=qcow2 size=42949672960 backing_file=/disk01.qcow2 cluster_size=65536 lazy_refcounts=off refcount_bits=16
SSH will be available on container port 2201.
VNC will be available on container port 5901.
VM MAC in the guest network will be 52:55:00:d1:55:01
VM IP in the guest network will be 192.168.66.101
VM hostname will be node01
mknod: missing operand after '10'   <========= looks like line 82 of base/scripts/vm.sh
Try 'mknod --help' for more information.
```

Is this expected and if so, could the log line be more verbose in what's missing?

**Comment by copejon** [comment]
@rmohr Thanks,  that's pointed in what looks like the right direction.  I've installed kvm.   Also, centos7.5 is running in VMware on my OS X host w/ nested virtualization enabled.

I'm getting a new error now related to iptables.  I'ved tried `iptables -F` as well as running with firewalld started and stopped.  The result is the same -

```
[root@centos ~]# gocli run --random-ports --nodes 3 --background kubevirtci/k8s-1.10.3
{"status":"Status: Image is up to date for docker.io/kubevirtci/k8s-1.10.3:latest"}Error response from daemon: driver failed programming external connectivity on endpoint kubevirt-dnsmasq (2c6d779f54ed159c3ffe288156c916d448d2c537f5dd2c3bd5dbc82dd4080e42):  (iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 32847 -j DNAT --to-destination 172.17.0.2:8443 ! -i docker0: iptables: No chain/target/match by that name.
 (exit status 1))
```

**Comment by rmohr** [comment]
This one is indeed a docker/firewall issue. I think that if you start the current versions for rhel/centos in the wrong order firewalld overwrites some docker  iptable rules. Restarting docker should do the trick.

**Comment by copejon** [comment]
Good news - that fixed the error
Bad news - another error.  Some [googling](https://bugs.launchpad.net/qemu/+bug/1661386) seems to indicate this is an error specific to using qemu/kvm on VMware machines, which I'm doing.

If you agree with the above, then I'll close the issue as it wouldn't relate to kubevirtci anymore.

```
[root@centos kubevirtci]# docker logs kubevirt-node01
3: tap01: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast master br0 state DOWN mode DEFAULT group default qlen 1000
    link/ether d2:12:b1:a3:5a:85 brd ff:ff:ff:ff:ff:ff
Creating disk "/var/run/disk/disk.qcow2 backed by /disk01.qcow2".
Formatting '/var/run/disk/disk.qcow2', fmt=qcow2 size=42949672960 backing_file=/disk01.qcow2 cluster_size=65536 lazy_refcounts=off refcount_bits=16
SSH will be available on container port 2201.
VNC will be available on container port 5901.
VM MAC in the guest network will be 52:55:00:d1:55:01
VM IP in the guest network will be 192.168.66.101
VM hostname will be node01
qemu-system-x86_64: error: failed to set MSR 0x38d to 0x0
qemu-system-x86_64: /builddir/build/BUILD/qemu-2.10.1/target/i386/kvm.c:1788: kvm_put_msrs: Assertion `ret == cpu->kvm_msr_buf->nmsrs' failed.
```

**Comment by rmohr** [comment]
> If you agree with the above, then I'll close the issue as it wouldn't relate to kubevirtci anymore.

Works ofr me. If you find  solutin to fix this /dev/kvm thing, let us know there is something we can change to make this work.

**Comment by copejon** [comment]
Going to go ahead and close - this isn't related to kubevirtci
