### ISSUE TITLE
Support for Vhostuser tests

### ISSUE THREAD

**Issue by krsacme** [kubevirt/kubevirtci#365]
This issue captures the changes required in order to support Vhostuser (OvS-DPDK) in kubevirtci. PR kubevirt/kubevirt#3208 adds the support for creating a VM with an additional interface based on vhotuser port to a OvS netdev bridge. Following set of issues need to be addressed in order to enable testing of Vhostuser ports.

Provider & OvS RPM Build
------------------------------------
Fedora vagrant cloud image does not have in-built `uio` kernel modules, which is required for `igb_uio` kernel module for using DPDK. Centos 8 vagrant cloud image has `uio` driver. But `OpenvSwitch` with DPDK enabled is not available in either of them. RPM `OpenvSwitch` with DPDK should be built. RPM is required, because the spec file contains the user/group creation for accessing vhostuser ports between OvS and qemu. 

Hugepages for OvS and VM
------------------------------------
OvS-DPDK requires a minimum of 1GB of hugepages memory to initialize DPDK (it can be 2M or 1G sized hugepages). And VM should also be created with hugepages to allow userspace data transfer between OvS-DPDK and VM. The default configuration of 64 2M hugepages of centos provider is not enough.

PMD Driver (DPDK)
---------------------------
`igb_uio` kernel module is required to bind the nic to the PMD to allow DPDK to read and write on the nic. `igb_uio` is part of DPDK source code, which is not build by default. DPDK has to be built inorder to use this driver. Note that, `vfio-pci` could be used with vIOMMU enabled on Q35 machine, but it requires host changes. Using `igb_uio` is less intrusive to run CI on available machines.

**Comment by ormergi** [comment]
Hey, have you try to install `uio` kernel module at provision stage on `k8s-fedora-1.17.0` provider? 
Since we already have a provider with fedora OS nodes that we provision it could solve part of this issue.

Please feel free to reach out if you have question or need help :wink:

**Comment by krsacme** [comment]
> Hey, have you try to install `uio` kernel module at provision stage on `k8s-fedora-1.17.0` provider?
> Since we already have a provider with fedora OS nodes that we provision it could solve part of this issue.
> 
 Yes, I did start with fedora, but fedora is missing the `uio` kernel module, which is a dependency to use `igb_uio`. Here is the log from the local ci cluster:

```
/home/kubevirtci[master]# ./cluster-up/ssh.sh node02
2020/07/27 06:11:52 Waiting for host: 192.168.66.102:22
2020/07/27 06:11:52 Connected to tcp://192.168.66.102:22
[vagrant@node02 ~]$ sudo su -
[root@node02 ~]# modprobe uio
modprobe: FATAL: Module uio not found in directory /lib/modules/5.3.7-301.fc31.x86_64
[root@node02 ~]# cat /etc/redhat-release
Fedora release 31 (Thirty One)
```
Because of it, I moved to centos. But, what do you think that can be avoideded between fedora vs centos? IMO, none of the steps (associated with linked PRs) can be skipped even for fedora. OvS does have DPDK, so it has to be built. Did I miss anything (can you specify the steps with associated PRs) ? I will ping you on slack.
