### ISSUE TITLE
Potential race in gocli

### ISSUE THREAD

**Issue by danielBelenky** [kubevirt/kubevirtci#375]
Recently, we see the following error during cluster up:

```
Error response from daemon: cannot join network of a non running container: 9419952d48bd39f4654d004aac29170ed02e8c3cfe762f953dab0506ae634095
```

I was not able to reproduce this error locally yet, so it might be related to
the CI cluster.

My assumption so far is that this is a race in gocli. We try to spawn a container
in the same netns with the `dnsmasq` container that is supposed to hold the namespace before it is actually running.

So far, I've noticed it only with the K8s 1.17 lane but other lanes might
be affected as well.

cc: @EdDev

**Comment by oshoval** [comment]
can be closed, it was that max_user_watches
