### ISSUE TITLE
Kubevirtci K8s providers need ipv6 enabled in the host machine

### ISSUE THREAD

**Issue by oshoval** [kubevirt/kubevirtci#411]
Since the base image of Centos 8 was updated to support dual stack, 
it require IPv6 to be enabled in the host machine.
without it, the dnsmasq container would fail to start, and the cluster-up will fail as well due to it.

RHEL 8 CSB comes with ipv6 disabled by default.
IPv6 can be enabled by updating to `ipv6.disable=0` in the grub, and the cluster will load successfully.

Possible Ref:
https://linuxconfig.org/redhat-8-enable-disable-ipv6

Affects K8s-1.17 / 1.18
Will update the docs about it.
As discussed with Petr, no need to keep 2 different base images (if needed we might consider one with auto detection on the ipv4 lane once we create the new dual stack lane).

**Comment by maiqueb** [comment]
@oshoval was this addressed ? Should we re-open ?
