### ISSUE TITLE
Suggestion, yaml modifier

### ISSUE THREAD

**Issue by oshoval** [kubevirt/kubevirtci#414]
Due to the work on dual stack, one sonobuoy conformance test is failing,
and it seems its the portmap CNI,
update to Calico might fix it.
While doing that i saw that the new Calico version changed a lot of things, and we also have some custom changes,
merging manually prone for errors, for example if we forget the scc.

I suggest a method which will do the following,
1. a base official file, pinned to a specific version. i.e 3.12.0 (until the base would change),
will be available in the repo.
2. a script that will take [1] and update our custom fields, generating the actual file we use with provision.
(the script will need strict matching)

This way updating the plugin, would be smooth, and we will just need to refetch [1] and make sure [2] produces the desired changes (which will be reflected in the PR of the updating).

**Comment by phoracek** [comment]
Have you checked whether bump in Calico fixes the issue, so we know it is worth it?

**Comment by oshoval** [comment]
> Have you checked whether bump in Calico fixes the issue, so we know it is worth it?

i am on it, manually,  will report,
on any case, i think it worth considering, since from what i know cni.yaml is in provision without the original one
but lets first focus on the line above.
