### ISSUE TITLE
KubeVirtCi failing on cluster-up with 'binding device to vfio driver failed'

### ISSUE THREAD

**Issue by dhiller** [kubevirt/kubevirtci#457]
Excerpt from the job log:
```
06:18:23:  + export QEMU_AUDIO_DRV=none
06:18:23:  + QEMU_AUDIO_DRV=none
06:18:23: � + exec qemu-system-x86_64 -enable-kvm -drive format=qcow2,file=/var/run/disk/disk.qcow2,if=virtio,cache=unsafe -device virtio-net-pci,netdev=network0,mac=52:55:00:d1:55:02 -netdev tap,id=network0,ifname=tap02,script=no,downscript=no -device virtio-rng-pci -vnc :02 -cpu host -m 10240M -smp 6 -serial pty -M q35,accel=kvm,kernel_irqchip=split -device intel-iommu,intremap=on,caching-mode=on -soundhw hda
06:18:23: 6 char device redirected to /dev/pts/0 (label serial0)
06:18:23: volume: pull-kubevirt-e2e-windows2016-node01
06:18:23: volume: pull-kubevirt-e2e-windows2016-node02
06:18:23: binding device to vfio driver failed
Makefile:113: recipe for target 'cluster-up' failed
make: *** [cluster-up] Error 1
```

Seen on two presubmits at least:

* https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/batch/pull-kubevirt-e2e-windows2016/1318796169635172352
* https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4392/pull-kubevirt-e2e-k8s-1.18/1318654239735549952/build-log.txt

/cc @vladikr @jean-edouard

**Comment by vladikr** [comment]
looking

**Comment by vladikr** [comment]
I don't see anything obvious at first glance...
Seems like some kind of flakiness because I that these jobs have passed eventually.
I'll try to reproduce locally.

**Comment by vladikr** [comment]
I think the problem is not the `prepareDeviceForAssignment` itself but we just didn't manage to ssh into the VM and this function reported the error first...

**Comment by maya-r** [comment]
/close
I have seen this in CDI in the past, updating kubevirtci made the problem go away. I believe this is already fixed.

**Comment by oshoval** [comment]
Hi, looks like this or a variant of it returned
https://search.ci.kubevirt.io/?search=binding+device+to+vfio+driver+failed&maxAge=336h&context=1&type=build-log&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job

as saw with @fgimenez

**Comment by fgimenez** [comment]
Yep, thanks for raising this @oshoval. It is affecting a lot of builds lately, links to a few failing jobs:
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/6793/pull-kubevirt-e2e-windows2016/1460520163156692992
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/6793/pull-kubevirt-e2e-windows2016/1460156100434202624
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/6737/pull-kubevirt-e2e-windows2016/1459128890243944448
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/6314/pull-kubevirt-e2e-k8s-1.22-sig-compute/1460517357989400576
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/6800/pull-kubevirt-e2e-k8s-1.20-operator-nonroot/1460382542845710336
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/2018/pull-containerized-data-importer-e2e-k8s-1.22-hpp-istio/1459905800834125824
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/6783/pull-kubevirt-e2e-k8s-1.20-sig-network/1459124628155797504
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/6670/pull-kubevirt-e2e-k8s-1.22-operator/1459104313900011520
* https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/batch/pull-kubevirt-e2e-k8s-1.20-sig-compute/1458856495247527936

**Comment by maya-r** [comment]
I wonder if we would benefit from a short sleep between binding the device to vfio-pci and checking if it is bound

**Comment by ormergi** [comment]
> I wonder if we would benefit from a short sleep between binding the device to vfio-pci and checking if it is bound (just before the end of cluster-provision/k8s/*/bind_device_to_vfio.sh)

@maya-r I dont think it will matter, on the SRIOV provider we do something similar
[[1]](https://github.com/kubevirt/kubevirtci/blob/main/cluster-up/cluster/kind-1.19-sriov/sriov-node/configure_vfs.sh#L97-L103), [[2]](https://github.com/kubevirt/kubevirtci/blob/main/cluster-up/cluster/kind-1.19-sriov/sriov-node/configure_vfs.sh#L32-L48) its pretty stable w/o waiting between iterations.

**Comment by maya-r** [comment]
worth noting this was stable for several months too

**Comment by oshoval** [comment]
> worth noting this was stable for several months too

even kernel updating might cause it if the timing is changed,
please check here if it might reminds the same problem
https://github.com/kubevirt/kubevirtci/pull/465
this PR fixed the problem mentioned there back then
