### ISSUE TITLE
drop pack8s usage

### ISSUE THREAD

**Issue by dankenigsberg** [kubevirt/kubevirtci#569]
According to its author @fromanirh, pack8s was outclassed by podman itself, which now supports the docker rest API; TL;DR: he suggests to drop it and just switch to newer podman

**Comment by fromanirh** [comment]
`pack8s` was introduced much earlier than `podman` announced its plan to support a REST API compatible with docker (https://docs.podman.io/en/latest/_static/api.html) so it leveraged the now-deprecated varlink interface, which was recommended at time.

As it stands nowadays, varlink is slow, makes some tasks kubevirtci wants to do awkward and most important is deprecated.
So yes, I totally recommend archiving `pack8s` for good. Hopefully it was useful, but it did its time.
