### ISSUE TITLE
k8s-provider-common.sh: line 120: kubectl: command not found

### ISSUE THREAD

**Issue by matosatti** [kubevirt/kubevirtci#856]
After KubeVirt's commit:

commit 3e26fdf393cfefb265c4819812af1f97128858f9
Author: kubevirt-bot <kubevirtbot@redhat.com>
Date:   Thu Jul 7 09:19:39 2022 +0000

    Bump kubevirtci
    
    [111fd50 cnao, Bump to v0.77.0 on all supported providers](https://github.com/kubevirt/kubevirtci/pull/817)
    [010a2ec podman: Support non root user via root socket](https://github.com/kubevirt/kubevirtci/pull/824)
    [da6af04 kind providers: Support Podman auto detection](https://github.com/kubevirt/kubevirtci/pull/826)
    [5842a3c Update cluster provisioning image to fedora 36](https://github.com/kubevirt/kubevirtci/pull/799)

I am seeing:

[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Starting the kubelet
[kubelet-start] Waiting for the kubelet to perform the TLS Bootstrap...

This node has joined the cluster:
* Certificate signing request was sent to apiserver and a response was received.
* The Kubelet was informed of the new secure connection details.

Run 'kubectl get nodes' on the control-plane to see this node join the cluster.

+ mkdir -p /var/lib/rook
+ chcon -t container_file_t /var/lib/rook/path-to/kubevirt/cluster-up//cluster/k8s-provider-common.sh: line 120: kubectl: command not found

Which is expected since i do not have Kubernetes installed on the host.

**Comment by oshoval** [comment]
Hi
Can you try meanwhile please to install kubectl ? no need k8s as a whole
https://kubernetes.io/docs/tasks/tools
