### ISSUE TITLE
CI wont cover integration with Istio and Multus

### ISSUE THREAD

**Issue by ormergi** [kubevirt/kubevirtci#917]
At the current state, all check-provision jobs run k8s e2e conformance tests and a sub-set of Kubevirt tests.

The small sub-set of Kubevirt tests won't cover integration with external components we use and expect to work with Kubevirts such as [Mutltus](https://github.com/k8snetworkplumbingwg/multus-cni) and [Istio](https://github.com/istio/istio).

The results are breaking changes getting merged.
What worse is the fact that we discover that a breaking change was merged only after it got merged when a "bump-kubevirtci" PR at kubevirt/kubevirt is issued, which blocks the pipeline until resolved/reverted.

**Comment by oshoval** [comment]
Imo there are few options:
(they are not ortogonal)

1. Add few tests for sanity check, even just one istio atm.
2. Forget about it until next time, as it doesn't happen so much.
3. Implement a way that it will be easier to run manually a lane which checks deeper coverage.
Deeper coverage can be run a specific lane all in all, with the provisioned, not yet published provider,
or more tests which we can call conformance tier 2 something (that won't automatic run, but easy to run on CI on the kubevirtci PRs)

**Comment by maiqueb** [comment]
> Imo there are few options: (they are not ortogonal)
> 
> 1. Add few tests for sanity check, even just one istio atm.

Adding an istio test would do it, it's a fair compromise. 

> 2. Forget about it until next time, as it doesn't happen so much.
> 3. Implement a way that it will be easier to run manually a lane which checks deeper coverage.
>    Deeper coverage can be run a specific lane all in all, with the provisioned, not yet published provider,
>    or more tests which we can call conformance tier 2 something (that won't automatic run, but easy to run on CI on the kubevirtci PRs)
