### ISSUE TITLE
Do we need a separate provider for ipv6?

### ISSUE THREAD

**Issue by jean-edouard** [kubevirt/kubevirtci#938]
A quick diff between 1.25 and 1.25-ipv6 showed only PSA-related differences.
Do we still need special providers for ipv6 or could we maybe get rid of it in favor of runtime changes?
The recent fips lane shows that even rebooting nodes during cluster-up is possible, which means virtually anything should be achievable dynamically.

**Comment by brianmcarey** [comment]
@oshoval do you think this would be possible? It would reduce the number of providers that we have to publish and maintain which would be great.

**Comment by oshoval** [comment]
We do need to support single stack ipv6 but
basically I believe it is possible to do it dynamically
However i won't able to do it atm

https://github.com/kubevirt/kubevirtci/pull/806
https://github.com/kubevirt/kubevirtci/pull/808

Those might help as reference on the changes needed

**Comment by oshoval** [comment]
https://github.com/kubevirt/kubevirtci/pull/954
