### ISSUE TITLE
kubevirtCI concept

### ISSUE THREAD

**Issue by Vikash993468** [kubevirt/kubevirtci#993]
@brianmcarey 
According to the docs ,kubevirtCi performs test on several kubevirt configuartion .

But what range of tests kubevirtCI can perform? does it performs test on kubevirt usecases like live migration,vm provisioning etc. ?
what are inputs and outputs for any particular tests? 

do we have any detailed resources on that?

**Comment by brianmcarey** [comment]
Hi @Vikash993468  - you can reach out to me on the [#kubevirt-dev](https://app.slack.com/client/T09NY5SBT/C0163DT0R8X) channel on the kubernetes slack. Its generally better than issues when you are looking for information. 

I think I have seen you in the channel previously? 

I am going to close this issue and we can discuss on the slack channel. 

/close
